Homework2 churkin
bajburtskii/nodejs-internship pull request #10
Opened 2023-02-05 16:14 UTC by DavaPark

2023-02-06 07:23 UTC, bajburtskii commented on homework2/package.json
> +{
зачем тебе этот файл?

2023-02-06 07:27 UTC, bajburtskii commented on homework2/lesson_homework.js
> +var gradF = ((gradC * 9 / 5) + 32);
вынеси пожалуйста это в специальную функцию

2023-02-06 07:28 UTC, bajburtskii commented on homework2/lesson_homework.js
> +var gradC = 60;
не используй пожалуйста var в своем коде

2023-02-06 13:56 UTC, DavaPark commented on homework2/package.json
> +{
ну он шёл в комплекте

2023-02-06 17:05 UTC, bajburtskii commented on homework2/package.json
> +{
в комплекте с чем?)) не вижу его в ветке main

2023-02-06 21:26 UTC, DavaPark commented on homework2/package.json
> +{
ну когда я создавал проект, то json сам автоматом подгрузился

2023-02-08 14:51 UTC, bajburtskii commented on lesson3/lesson_3_homework_task_32.js
> +        count2 = array.length;
https://builtin.com/data-science/variable-names

здесь пара плохих практик относительно именования переменных, прочти это пожалуйста и исправь свой код в соотвествии с примерами отсюда

2023-02-08 14:53 UTC, bajburtskii commented on lesson3/task33.js
> +};
почему ты не делаешь дз в этиъ файлах, а создаешь отдельные?

2023-02-08 14:55 UTC, bajburtskii requested changes
проверб комментарии пожалуйста

2023-02-09 07:15 UTC, bajburtskii commented on lesson3/lesson_3_homework.js
> +a = a.replace(regex5,"");
я рпавильн понял, таким образом ты избавлялся от цифр в исходных переменных?

2023-02-09 07:16 UTC, bajburtskii commented on lesson3/lesson_3_homework.js
> +    return str === str.split('').reverse().join('');
это очень простой алгоритм и наверняка он рабочий.
для тренировки 
![1_dmbLFRJxggM6dAOm59MnAg](https://user-images.githubusercontent.com/1996929/217743655-81de4435-3e21-42e6-a055-c0eac8c17459.gif)
попробуй вот такой подход

2023-02-09 17:51 UTC, DavaPark commented on lesson3/lesson_3_homework.js
> +a = a.replace(regex5,"");
Да

2023-02-09 17:52 UTC, DavaPark commented on lesson3/task33.js
> +};
а я думал надо отдельно создавать файл, а это просто как файл с заданием, а с выполнением отдельный файл

2023-02-09 17:56 UTC, DavaPark commented on lesson3/lesson_3_homework.js
> +    return str === str.split('').reverse().join('');
хорошо,  я попытаюсь по другому решить

2023-02-09 18:24 UTC, bajburtskii commented on lesson3/lesson_3_homework.js
> +a = a.replace(regex5,"");
Сделай пожалуйста так чтобы твой код не был не был заточен на конкретные две строки, а работал для всех возможных случаев

2023-02-09 22:01 UTC, DavaPark commented on lesson3/lesson_3_homework.js
> +a = a.replace(regex5,"");
ну я могу просто ручками таким образом прописать все возможные исключения, но мне кажется вы ждёте от меня другого подхода да?

2023-02-13 09:30 UTC, bajburtskii commented on lesson3/lesson_3_homework.js
> +a = a.replace(regex5,"");
конечно, подход "просто ручками" не годится

2023-02-15 14:24 UTC, bajburtskii approved these changes

2023-03-01 21:25 UTC, closed without merging