Bordiian task32
bajburtskii/nodejs-internship pull request #16
Opened 2023-02-06 15:56 UTC by AbyssWalker1990

2023-02-06 16:58 UTC, bajburtskii commented on lesson3/task32.js
> +  let pref = strs.sort((a ,b) => { return a.length - b.length })[0] // Shortest word can be prefix
эту строку можно сократить

http://es6-features.org/#ExpressionBodies

2023-02-06 17:02 UTC, bajburtskii commented on lesson3/task32.js
> +  let pref = strs.sort((a ,b) => { return a.length - b.length })[0] // Shortest word can be prefix
если бы мы с тобой работали над настойщим проектом то прежде чем брать первый элемент из отсортированного массива нужно для начала убедиться что входные данные в принципе массив и соотвественно не пустой массив, потому как production код может удивлять.

Здесь по условию задачи мы условились что на вход приходих массив строк, но всегда нужно проверять все эти договоренности, потому что код пишут люди и ничто в данном случае не меашет мне отправить на вход не массив а просто одну строку или число.

2023-02-07 08:28 UTC, AbyssWalker1990 commented on lesson3/task32.js
> +  let pref = strs.sort((a ,b) => { return a.length - b.length })[0] // Shortest word can be prefix
Додав валідацію

2023-02-07 08:28 UTC, AbyssWalker1990 commented on lesson3/task32.js
> +  let pref = strs.sort((a ,b) => { return a.length - b.length })[0] // Shortest word can be prefix
Скоротив

2023-02-08 15:01 UTC, bajburtskii commented on lesson3/task32.js
> +  if (Array.isArray(strs) && strs.length >= 1) {
https://betterprogramming.pub/refactoring-guard-clauses-2ceeaa1a9da

почитай о технике описанной здесь. она называется guard close. по этим ключевым словам ты найдешь еще много доп информации.

После воспользуйся ею пожалуйста

2023-02-08 15:02 UTC, bajburtskii commented on lesson3/task32.js
> +  let pref = []
обрати внимание здесь у тебя объявлена как массив, а дальше она превращается в строку, жто не есть хорошо

2023-02-08 15:02 UTC, bajburtskii requested changes
оставил пару комментариев

2023-02-08 18:19 UTC, AbyssWalker1990 commented on lesson3/task32.js
> +  let pref = []
Виправив. У мене спочатку була думка робити це все через массиви, але майже зразу зрозумів що можу лишитись у string. Провтикав цей момент

2023-02-08 18:55 UTC, AbyssWalker1990 commented on lesson3/task32.js
> +  if (Array.isArray(strs) && strs.length >= 1) {
Трохи поправив. Вибачаюсь що нашвидкоруч, просто буду за компом наступний раз аж завтра ввечері. Я переправлю якщо щось не так і ОБОВ'ЯЗКОВО нормально розберусь з цією технікою

2023-02-22 16:49 UTC, AbyssWalker1990 commented
Зроблено

2023-02-27 09:22 UTC, bajburtskii approved these changes

2023-02-27 10:44 UTC, merged