Task21 solution
bajburtskii/nodejs-internship pull request #23
Opened 2023-02-08 11:48 UTC by MedvedevDev

Task 21 PR

2023-02-08 15:20 UTC, bajburtskii commented on lesson2/task21.js
> +}
разбей эту функцию на две, чтобы не приходилось заморачиваться с лишними проверками и параметрами

2023-02-08 15:21 UTC, bajburtskii requested changes
оставил комментарий

2023-02-13 10:55 UTC, MedvedevDev commented on lesson2/task21.js
> +}
функцию convertTemp ?

2023-02-13 11:12 UTC, bajburtskii commented on lesson2/task21.js
> +}
да

2023-02-13 11:28 UTC, MedvedevDev commented on lesson2/task21.js
> +}
@bajburtskii Сделал

2023-02-13 15:12 UTC, bajburtskii approved these changes

2023-02-13 17:00 UTC, merged