Bordiian task52 completed
bajburtskii/nodejs-internship pull request #29
Opened 2023-02-19 13:47 UTC by AbyssWalker1990

2023-02-20 10:36 UTC, bajburtskii commented on lesson5/task52.js
> +  };
Так сработает, для тренировки попробуй другой алгоритм

1+1=0 with carry 1
1+0=1 with carry 0
0+1=1 with carry 0
0+0=0 with carry 0
Imp:1+1=1 with carry 1 if previous carry was 1.

2023-02-20 10:37 UTC, bajburtskii commented on lesson5/task52.js
> +  };
т.е. нужно пройтись по каждому символу обоих строк и сложить биты по индексу, держа в голове логику выше

2023-02-20 10:37 UTC, bajburtskii requested changes
попробуй другой алгоритм

2023-02-21 07:35 UTC, AbyssWalker1990 commented on lesson5/task52.js
> +  };
Ок, спробую. Сьогодні не обіцяю, роботою завантажений. Завтра точно

2023-02-21 14:53 UTC, AbyssWalker1990 commented on lesson5/task52.js
> +  };
Реалізував нову логіку

2023-02-22 16:48 UTC, AbyssWalker1990 commented
Зроблено

2023-02-27 09:21 UTC, bajburtskii approved these changes

2023-02-27 10:45 UTC, merged