Task 52 solution
bajburtskii/nodejs-internship pull request #37
Opened 2023-02-21 22:03 UTC by MedvedevDev

2023-02-22 15:36 UTC, bajburtskii commented on lesson5/task52.js
>  const addBinary = function(a, b) {
для тренировки попробу вот такой алгоритм


1+1=0 with carry 1
1+0=1 with carry 0
0+1=1 with carry 0
0+0=0 with carry 0
Imp:1+1=1 with carry 1 if previous carry was 1.
The carry gets added in next step(scanning from right to left).

2023-02-22 15:36 UTC, bajburtskii requested changes
попробуй другой алгоритм

2023-02-22 17:58 UTC, MedvedevDev commented on lesson5/task52.js
>  const addBinary = function(a, b) {
@bajburtskii  Ok

2023-02-28 22:11 UTC, MedvedevDev commented on lesson5/task52.js
>  const addBinary = function(a, b) {
@bajburtskii добавил алгоритм

2023-03-06 13:59 UTC, bajburtskii approved these changes

2023-03-06 14:05 UTC, merged